/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SubmitProjectRouteImport } from './routes/submit-project'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForAgenciesRouteImport } from './routes/for-agencies'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmServiceRouteImport } from './routes/confirm-service'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgencyOnboardingRouteImport } from './routes/agency-onboarding'
import { Route as AgencyInboxRouteImport } from './routes/agency-inbox'
import { Route as AgencyDashboardRouteImport } from './routes/agency-dashboard'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgenciesIndexRouteImport } from './routes/agencies.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AgenciesSlugRouteImport } from './routes/agencies.$slug'
import { Route as PortfolioAgencySlugItemSlugRouteImport } from './routes/portfolio_.$agencySlug.$itemSlug'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitProjectRoute = SubmitProjectRouteImport.update({
  id: '/submit-project',
  path: '/submit-project',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgenciesRoute = ForAgenciesRouteImport.update({
  id: '/for-agencies',
  path: '/for-agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmServiceRoute = ConfirmServiceRouteImport.update({
  id: '/confirm-service',
  path: '/confirm-service',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyOnboardingRoute = AgencyOnboardingRouteImport.update({
  id: '/agency-onboarding',
  path: '/agency-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyInboxRoute = AgencyInboxRouteImport.update({
  id: '/agency-inbox',
  path: '/agency-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyDashboardRoute = AgencyDashboardRouteImport.update({
  id: '/agency-dashboard',
  path: '/agency-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgenciesRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesSlugRoute = AgenciesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AgenciesRoute,
} as any)
const PortfolioAgencySlugItemSlugRoute =
  PortfolioAgencySlugItemSlugRouteImport.update({
    id: '/portfolio_/$agencySlug/$itemSlug',
    path: '/portfolio/$agencySlug/$itemSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agencies': typeof AgenciesRouteWithChildren
  '/agency-dashboard': typeof AgencyDashboardRoute
  '/agency-inbox': typeof AgencyInboxRoute
  '/agency-onboarding': typeof AgencyOnboardingRoute
  '/blog': typeof BlogRoute
  '/confirm-service': typeof ConfirmServiceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/enterprise': typeof EnterpriseRoute
  '/for-agencies': typeof ForAgenciesRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/portfolio': typeof PortfolioRoute
  '/submit-project': typeof SubmitProjectRoute
  '/upgrade': typeof UpgradeRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/leads/$id': typeof LeadsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/portfolio/$agencySlug/$itemSlug': typeof PortfolioAgencySlugItemSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agency-dashboard': typeof AgencyDashboardRoute
  '/agency-inbox': typeof AgencyInboxRoute
  '/agency-onboarding': typeof AgencyOnboardingRoute
  '/blog': typeof BlogRoute
  '/confirm-service': typeof ConfirmServiceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/enterprise': typeof EnterpriseRoute
  '/for-agencies': typeof ForAgenciesRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/portfolio': typeof PortfolioRoute
  '/submit-project': typeof SubmitProjectRoute
  '/upgrade': typeof UpgradeRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/leads/$id': typeof LeadsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/agencies': typeof AgenciesIndexRoute
  '/portfolio/$agencySlug/$itemSlug': typeof PortfolioAgencySlugItemSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agencies': typeof AgenciesRouteWithChildren
  '/agency-dashboard': typeof AgencyDashboardRoute
  '/agency-inbox': typeof AgencyInboxRoute
  '/agency-onboarding': typeof AgencyOnboardingRoute
  '/blog': typeof BlogRoute
  '/confirm-service': typeof ConfirmServiceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/enterprise': typeof EnterpriseRoute
  '/for-agencies': typeof ForAgenciesRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/portfolio': typeof PortfolioRoute
  '/submit-project': typeof SubmitProjectRoute
  '/upgrade': typeof UpgradeRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/leads/$id': typeof LeadsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/portfolio_/$agencySlug/$itemSlug': typeof PortfolioAgencySlugItemSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agencies'
    | '/agency-dashboard'
    | '/agency-inbox'
    | '/agency-onboarding'
    | '/blog'
    | '/confirm-service'
    | '/contact'
    | '/dashboard'
    | '/enterprise'
    | '/for-agencies'
    | '/login'
    | '/payment-success'
    | '/portfolio'
    | '/submit-project'
    | '/upgrade'
    | '/agencies/$slug'
    | '/blog/$slug'
    | '/leads/$id'
    | '/projects/$id'
    | '/agencies/'
    | '/portfolio/$agencySlug/$itemSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agency-dashboard'
    | '/agency-inbox'
    | '/agency-onboarding'
    | '/blog'
    | '/confirm-service'
    | '/contact'
    | '/dashboard'
    | '/enterprise'
    | '/for-agencies'
    | '/login'
    | '/payment-success'
    | '/portfolio'
    | '/submit-project'
    | '/upgrade'
    | '/agencies/$slug'
    | '/blog/$slug'
    | '/leads/$id'
    | '/projects/$id'
    | '/agencies'
    | '/portfolio/$agencySlug/$itemSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agencies'
    | '/agency-dashboard'
    | '/agency-inbox'
    | '/agency-onboarding'
    | '/blog'
    | '/confirm-service'
    | '/contact'
    | '/dashboard'
    | '/enterprise'
    | '/for-agencies'
    | '/login'
    | '/payment-success'
    | '/portfolio'
    | '/submit-project'
    | '/upgrade'
    | '/agencies/$slug'
    | '/blog_/$slug'
    | '/leads/$id'
    | '/projects/$id'
    | '/agencies/'
    | '/portfolio_/$agencySlug/$itemSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgenciesRoute: typeof AgenciesRouteWithChildren
  AgencyDashboardRoute: typeof AgencyDashboardRoute
  AgencyInboxRoute: typeof AgencyInboxRoute
  AgencyOnboardingRoute: typeof AgencyOnboardingRoute
  BlogRoute: typeof BlogRoute
  ConfirmServiceRoute: typeof ConfirmServiceRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EnterpriseRoute: typeof EnterpriseRoute
  ForAgenciesRoute: typeof ForAgenciesRoute
  LoginRoute: typeof LoginRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PortfolioRoute: typeof PortfolioRoute
  SubmitProjectRoute: typeof SubmitProjectRoute
  UpgradeRoute: typeof UpgradeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LeadsIdRoute: typeof LeadsIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  PortfolioAgencySlugItemSlugRoute: typeof PortfolioAgencySlugItemSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-project': {
      id: '/submit-project'
      path: '/submit-project'
      fullPath: '/submit-project'
      preLoaderRoute: typeof SubmitProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agencies': {
      id: '/for-agencies'
      path: '/for-agencies'
      fullPath: '/for-agencies'
      preLoaderRoute: typeof ForAgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-service': {
      id: '/confirm-service'
      path: '/confirm-service'
      fullPath: '/confirm-service'
      preLoaderRoute: typeof ConfirmServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-onboarding': {
      id: '/agency-onboarding'
      path: '/agency-onboarding'
      fullPath: '/agency-onboarding'
      preLoaderRoute: typeof AgencyOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-inbox': {
      id: '/agency-inbox'
      path: '/agency-inbox'
      fullPath: '/agency-inbox'
      preLoaderRoute: typeof AgencyInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-dashboard': {
      id: '/agency-dashboard'
      path: '/agency-dashboard'
      fullPath: '/agency-dashboard'
      preLoaderRoute: typeof AgencyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/$slug': {
      id: '/agencies/$slug'
      path: '/$slug'
      fullPath: '/agencies/$slug'
      preLoaderRoute: typeof AgenciesSlugRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/portfolio_/$agencySlug/$itemSlug': {
      id: '/portfolio_/$agencySlug/$itemSlug'
      path: '/portfolio/$agencySlug/$itemSlug'
      fullPath: '/portfolio/$agencySlug/$itemSlug'
      preLoaderRoute: typeof PortfolioAgencySlugItemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgenciesRouteChildren {
  AgenciesSlugRoute: typeof AgenciesSlugRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
}

const AgenciesRouteChildren: AgenciesRouteChildren = {
  AgenciesSlugRoute: AgenciesSlugRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
}

const AgenciesRouteWithChildren = AgenciesRoute._addFileChildren(
  AgenciesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgenciesRoute: AgenciesRouteWithChildren,
  AgencyDashboardRoute: AgencyDashboardRoute,
  AgencyInboxRoute: AgencyInboxRoute,
  AgencyOnboardingRoute: AgencyOnboardingRoute,
  BlogRoute: BlogRoute,
  ConfirmServiceRoute: ConfirmServiceRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EnterpriseRoute: EnterpriseRoute,
  ForAgenciesRoute: ForAgenciesRoute,
  LoginRoute: LoginRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PortfolioRoute: PortfolioRoute,
  SubmitProjectRoute: SubmitProjectRoute,
  UpgradeRoute: UpgradeRoute,
  BlogSlugRoute: BlogSlugRoute,
  LeadsIdRoute: LeadsIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  PortfolioAgencySlugItemSlugRoute: PortfolioAgencySlugItemSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
